module.exports = [
  {
    hanzi: "爱",
    pinyin: "ài",
    translations: ["to love"],
    category: "verbs",
  },
  {
    hanzi: "八",
    pinyin: "bā",
    translations: ["eight", "8"],
    category: "numbers",
  },
  {
    hanzi: "爸爸",
    pinyin: "bà ba",
    translations: ["father"],
    category: "nouns",
  },
  {
    hanzi: "杯子",
    pinyin: "bēi zi",
    translations: ["cup", "glass"],
    category: "nouns",
  },
  {
    hanzi: "北京",
    pinyin: "Běi jīng",
    translations: ["Beijing"],
    category: "nouns",
  },
  {
    hanzi: "本",
    pinyin: "běn",
    translations: ["classifier for books", "origin"],
    category: "classifiers",
  },
  {
    hanzi: "不客气",
    pinyin: "bù kè qi",
    translations: ["you're welcome"],
    category: "verbs",
  },
  {
    hanzi: "不",
    pinyin: "bù",
    translations: ["(negative prefix)", "no"],
    category: "adverbs",
  },
  {
    hanzi: "菜",
    pinyin: "cài",
    translations: ["dish (type of food)", "vegetables"],
    category: "nouns",
  },
  {
    hanzi: "茶",
    pinyin: "chá",
    translations: ["tea"],
    category: "nouns",
  },
  {
    hanzi: "吃",
    pinyin: "chī",
    translations: ["to eat"],
    category: "verbs",
  },
  {
    hanzi: "出租车",
    pinyin: "chū zū chē",
    translations: ["taxi"],
    category: "nouns",
  },
  {
    hanzi: "打电话",
    pinyin: "dǎ diàn huà",
    translations: ["to make a telephone call"],
    category: "verbs",
  },
  {
    id: 14,
    hanzi: "大",
    pinyin: "dà",
    translations: ["big", "oldest"],
    category: "adjective",
  },
  {
    hanzi: "的",
    pinyin: "de",
    translations: ["of", "(possessive particle)", "(used after an attribute)"],
    category: "others",
  },
  {
    hanzi: "点",
    pinyin: "diǎn",
    translations: ["point", "dot", "o'clock"],
    category: "nouns",
  },
  {
    hanzi: "电脑",
    pinyin: "diàn nǎo",
    translations: ["computer"],
    category: "nouns",
  },
  {
    hanzi: "电视",
    pinyin: "diàn shì",
    translations: ["television", "TV"],
    category: "nouns",
  },
  {
    hanzi: "电影",
    pinyin: "diàn yǐng",
    translations: ["movie", "film"],
    category: "nouns",
  },
  {
    hanzi: "东西",
    pinyin: "dōng xi",
    translations: ["thing", "stuff"],
    category: "nouns",
  },
  {
    hanzi: "都",
    pinyin: "dōu",
    translations: ["all", "both", "(not) at all"],
    category: "adverbs",
  },
  {
    hanzi: "读",
    pinyin: "dú",
    translations: ["to read", "to study"],
    category: "nouns",
  },
  {
    hanzi: "对不起",
    pinyin: "duì bu qǐ",
    translations: ["I'm sorry", "excuse me"],
    category: "nouns",
  },
  {
    hanzi: "多",
    pinyin: "duō",
    translations: ["many", "much"],
    category: "nouns",
  },
  {
    hanzi: "多少",
    pinyin: "duō shao",
    translations: ["how much", "how many"],
    category: "pronouns",
  },
  {
    hanzi: "儿子",
    pinyin: "ér zi",
    translations: ["son"],
    category: "nouns",
  },
  {
    hanzi: "二",
    pinyin: "èr",
    translations: ["two", "2"],
    category: "numbers",
  },
  {
    hanzi: "饭馆",
    pinyin: "fàn guǎn",
    translations: ["restaurant", "CL:家[jiā]"],
    category: "nouns",
  },
  {
    hanzi: "飞机",
    pinyin: "fēi jī",
    translations: ["airplane", "CL:架[jià]"],
    category: "nouns",
  },
  {
    hanzi: "分钟",
    pinyin: "fēn zhōng",
    translations: ["minute"],
    category: "nouns",
  },
  {
    hanzi: "高兴",
    pinyin: "gāo xìng",
    translations: [
      "happy",
      "glad",
      "willing (to do sth)",
      "in a cheerful mood",
    ],
    category: "adjectives",
  },
  {
    hanzi: "个",
    pinyin: "gè",
    translations: ["a", "an", "one"],
    category: "classifiers",
  },
  {
    hanzi: "工作",
    pinyin: "gōng zuò",
    translations: ["to work"],
    category: "verbs",
  },
  {
    hanzi: "狗",
    pinyin: "gǒu",
    translations: ["dog"],
    category: "nouns",
  },
  {
    hanzi: "汉语",
    pinyin: "Hàn yǔ",
    translations: ["Chinese language"],
    category: "nouns",
  },
  {
    hanzi: "好",
    pinyin: "hǎo",
    translations: ["good", "well"],
    category: "adjectives",
  },
  {
    hanzi: "喝",
    pinyin: "hē",
    translations: ["to drink"],
    category: "verbs",
  },
  {
    hanzi: "和",
    pinyin: "hé",
    translations: ["and"],
    category: "others",
  },
  {
    hanzi: "很",
    pinyin: "hěn",
    translations: ["quite", "very"],
    category: "adverbs",
  },
  {
    hanzi: "后面",
    pinyin: "hòu mian",
    translations: ["behind", "later"],
    category: "nouns",
  },
  {
    hanzi: "回",
    pinyin: "huí",
    translations: ["to return"],
    category: "verbs",
  },
  {
    hanzi: "会",
    pinyin: "huì",
    translations: ["can", "be able to", "will"],
    category: "verbs",
  },
  {
    hanzi: "火车站",
    pinyin: "huǒ chē zhàn",
    translations: ["train station"],
    category: "nouns",
  },
  {
    hanzi: "几",
    pinyin: "jǐ",
    translations: ["how much", "how many", "a few"],
    category: "pronouns",
  },
  {
    hanzi: "家",
    pinyin: "jiā",
    translations: ["home", "family"],
    category: "nouns",
  },
  {
    hanzi: "叫",
    pinyin: "jiào",
    translations: ["to call"],
    category: "verbs",
  },
  {
    hanzi: "今天",
    pinyin: "jīn tiān",
    translations: ["today", "at the present", "now"],
    category: "nouns",
  },
  {
    hanzi: "九",
    pinyin: "jiǔ",
    translations: ["nine", "9"],
    category: "numbers",
  },
  {
    hanzi: "开",
    pinyin: "kāi",
    translations: ["to open", "to start", "to turn on"],
    category: "verbs",
  },
  {
    hanzi: "看",
    pinyin: "kàn",
    translations: ["to see", "to read", "to watch"],
    category: "verbs",
  },
  {
    hanzi: "看见",
    pinyin: "kàn jiàn",
    translations: ["to see"],
    category: "verbs",
  },
  {
    hanzi: "块",
    pinyin: "kuài",
    translations: ["piece"],
    category: "classifiers",
  },
  {
    hanzi: "来",
    pinyin: "lái",
    translations: ["to come", "to arrive"],
    category: "verbs",
  },
  {
    hanzi: "老师",
    pinyin: "lǎo shī",
    translations: ["teacher"],
    category: "nouns",
  },
  {
    hanzi: "了",
    pinyin: "le",
    translations: ["(completed action marker)"],
    category: "others",
  },
  {
    hanzi: "冷",
    pinyin: "lěng",
    translations: ["cold"],
    category: "adjectives",
  },
  {
    hanzi: "里",
    pinyin: "lǐ",
    translations: ["inside", "inner"],
    category: "nouns",
  },
  {
    hanzi: "零",
    pinyin: "líng",
    translations: ["zero", "0"],
    category: "numbers",
  },
  {
    hanzi: "六",
    pinyin: "liù",
    translations: ["six", "6"],
    category: "numbers",
  },
  {
    hanzi: "妈妈",
    pinyin: "mā ma",
    translations: ["mother"],
    category: "nouns",
  },
  {
    hanzi: "吗",
    pinyin: "ma",
    translations: ["(question tag)"],
    category: "others",
  },
  {
    hanzi: "买",
    pinyin: "mǎi",
    translations: ["to buy", "to purchase"],
    category: "verbs",
  },
  {
    hanzi: "猫",
    pinyin: "māo",
    translations: ["cat"],
    category: "nouns",
  },
  {
    hanzi: "没",
    pinyin: "méi",
    translations: ["have not", "not"],
    category: "adverbs",
  },
  {
    hanzi: "没关系",
    pinyin: "méi guān xi",
    translations: ["it doesn't matter"],
    category: "verbs",
  },
  {
    hanzi: "米饭",
    pinyin: "mǐ fàn",
    translations: ["(cooked) rice"],
    category: "nouns",
  },
  {
    hanzi: "明天",
    pinyin: "míng tiān",
    translations: ["tomorrow"],
    category: "nouns",
  },
  {
    hanzi: "名字",
    pinyin: "míng zi",
    translations: ["name"],
    category: "nouns",
  },
  {
    hanzi: "哪",
    pinyin: "nǎ",
    translations: ["how", "which"],
    category: "pronouns",
  },
  {
    hanzi: "那",
    pinyin: "nà",
    translations: ["that", "there"],
    category: "pronouns",
  },
  {
    hanzi: "呢",
    pinyin: "ne",
    translations: ['particle to ask ("What about ...?", "And ...?")'],
    category: "others",
  },
  {
    hanzi: "能",
    pinyin: "néng",
    translations: ["to be able to", "to be capable of"],
    category: "verbs",
  },
  {
    hanzi: "你",
    pinyin: "nǐ",
    translations: ["you (informal)"],
    category: "pronouns",
  },
  {
    hanzi: "年",
    pinyin: "nián",
    translations: ["year"],
    category: "nouns",
  },
  {
    hanzi: "女儿",
    pinyin: "nǚ ér",
    translations: ["daughter"],
    category: "nouns",
  },
  {
    hanzi: "朋友",
    pinyin: "péng you",
    translations: ["friend"],
    category: "nouns",
  },
  {
    hanzi: "漂亮",
    pinyin: "piào liang",
    translations: ["pretty", "beautiful"],
    category: "adjectives",
  },
  {
    hanzi: "苹果",
    pinyin: "píng guǒ",
    translations: ["apple"],
    category: "nouns",
  },
  {
    hanzi: "七",
    pinyin: "qī",
    translations: ["seven", "7"],
    category: "numbers",
  },
  {
    hanzi: "钱",
    pinyin: "qián",
    translations: ["money"],
    category: "nouns",
  },
  {
    hanzi: "前面",
    pinyin: "qián miàn",
    translations: ["ahead", "preceding"],
    category: "nouns",
  },
  {
    hanzi: "请",
    pinyin: "qǐng",
    translations: ["please (do sth)", "to request"],
    category: "verbs",
  },
  {
    hanzi: "去",
    pinyin: "qù",
    translations: ["to go"],
    category: "verbs",
  },
  {
    hanzi: "热",
    pinyin: "rè",
    translations: ["hot"],
    category: "adjectives",
  },
  {
    hanzi: "人",
    pinyin: "rén",
    translations: ["person", "people"],
    category: "nouns",
  },
  {
    hanzi: "认识",
    pinyin: "rèn shi",
    translations: ["to know", "to get acquainted with sb"],
    category: "verbs",
  },
  {
    hanzi: "日",
    pinyin: "rì",
    translations: ["sun", "day"],
    category: "nouns",
  },
  {
    hanzi: "三",
    pinyin: "sān",
    translations: ["three", "3"],
    category: "numbers",
  },
  {
    hanzi: "商店",
    pinyin: "shāng diàn",
    translations: ["store", "shop"],
    category: "nouns",
  },
  {
    hanzi: "上",
    pinyin: "shàng",
    translations: ["on top", "up"],
    category: "nouns",
  },
  {
    hanzi: "上午",
    pinyin: "shàng wǔ",
    translations: ["morning"],
    category: "nouns",
  },
  {
    hanzi: "少",
    pinyin: "shǎo",
    translations: ["few", "little", "lack"],
    category: "adjectives",
  },
  {
    hanzi: "谁",
    pinyin: "shéi",
    translations: ["who"],
    category: "pronouns",
  },
  {
    hanzi: "什么",
    pinyin: "shén me",
    translations: ["what?", "why?"],
    category: "pronouns",
  },
  {
    hanzi: "十",
    pinyin: "shí",
    translations: ["ten", "10"],
    category: "numbers",
  },
  {
    hanzi: "时候",
    pinyin: "shí hou",
    translations: ["time", "moment"],
    category: "nouns",
  },
  {
    hanzi: "是",
    pinyin: "shì",
    translations: ["to be (am, is, are)"],
    category: "verbs",
  },
  {
    hanzi: "书",
    pinyin: "shū",
    translations: ["book"],
    category: "nouns",
  },
  {
    hanzi: "水",
    pinyin: "shuǐ",
    translations: ["water"],
    category: "nouns",
  },
  {
    hanzi: "水果",
    pinyin: "shuǐ guǒ",
    translations: ["fruit"],
    category: "nouns",
  },
  {
    hanzi: "睡觉",
    pinyin: "shuì jiào",
    translations: ["to go to bed", "to sleep"],
    category: "verbs",
  },
  {
    hanzi: "说话",
    pinyin: "shuō huà",
    translations: ["to speak"],
    category: "verbs",
  },
  {
    hanzi: "四",
    pinyin: "sì",
    translations: ["four", "4"],
    category: "numbers",
  },
  {
    hanzi: "岁",
    pinyin: "suì",
    translations: ["year"],
    category: "classifiers",
  },
  {
    hanzi: "他",
    pinyin: "tā",
    translations: ["he"],
    category: "pronouns",
  },
  {
    hanzi: "她",
    pinyin: "tā",
    translations: ["she"],
    category: "pronouns",
  },
  {
    hanzi: "太",
    pinyin: "tài",
    translations: ["too (much)", "very"],
    category: "adverbs",
  },
  {
    hanzi: "天气",
    pinyin: "tiān qì",
    translations: ["weather"],
    category: "nouns",
  },
  {
    hanzi: "听",
    pinyin: "tīng",
    translations: ["to listen"],
    category: "verbs",
  },
  {
    hanzi: "同学",
    pinyin: "tóng xué",
    translations: ["classmate"],
    category: "nouns",
  },
  {
    hanzi: "喂",
    pinyin: "wèi",
    translations: ["hello (phone)"],
    category: "others",
  },
  {
    hanzi: "我",
    pinyin: "wǒ",
    translations: ["I"],
    category: "pronouns",
  },
  {
    hanzi: "我们",
    pinyin: "wǒ men",
    translations: ["we"],
    category: "pronouns",
  },
  {
    hanzi: "五",
    pinyin: "wǔ",
    translations: ["five", "5"],
    category: "numbers",
  },
  {
    hanzi: "喜欢",
    pinyin: "xǐ huan",
    translations: ["to like", "to be fond of"],
    category: "verbs",
  },
  {
    hanzi: "下",
    pinyin: "xià",
    translations: ["down"],
    category: "nouns",
  },
  {
    hanzi: "下午",
    pinyin: "xià wǔ",
    translations: ["afternoon"],
    category: "nouns",
  },
  {
    hanzi: "下雨",
    pinyin: "xià yǔ",
    translations: ["to rain", "rainy"],
    category: "verbs",
  },
  {
    hanzi: "先生",
    pinyin: "xiān sheng",
    translations: ["sir", "husband"],
    category: "nouns",
  },
  {
    hanzi: "现在",
    pinyin: "xiàn zài",
    translations: ["now"],
    category: "nouns",
  },
  {
    hanzi: "想",
    pinyin: "xiǎng",
    translations: ["to think", "to miss"],
    category: "verbs",
  },
  {
    hanzi: "小",
    pinyin: "xiǎo",
    translations: ["small"],
    category: "adjectives",
  },
  {
    hanzi: "小姐",
    pinyin: "xiǎo jie",
    translations: ["young lady", "miss"],
    category: "nouns",
  },
  {
    hanzi: "些",
    pinyin: "xiē",
    translations: ["some"],
    category: "classifiers",
  },
  {
    hanzi: "写",
    pinyin: "xiě",
    translations: ["to write"],
    category: "verbs",
  },
  {
    hanzi: "谢谢",
    pinyin: "xiè xie",
    translations: ["to thank", "thanks"],
    category: "verbs",
  },
  {
    hanzi: "星期",
    pinyin: "xīng qī",
    translations: ["week"],
    category: "nouns",
  },
  {
    hanzi: "学生",
    pinyin: "xué sheng",
    translations: ["student"],
    category: "nouns",
  },
  {
    hanzi: "学习",
    pinyin: "xué xí",
    translations: ["to learn", "to study"],
    category: "verbs",
  },
  {
    hanzi: "学校",
    pinyin: "xué xiào",
    translations: ["school"],
    category: "nouns",
  },
  {
    hanzi: "一",
    pinyin: "yī",
    translations: ["one", "1"],
    category: "numbers",
  },
  {
    hanzi: "衣服",
    pinyin: "yī fu",
    translations: ["clothes"],
    category: "nouns",
  },
  {
    hanzi: "医生",
    pinyin: "yī shēng",
    translations: ["doctor"],
    category: "nouns",
  },
  {
    hanzi: "医院",
    pinyin: "yī yuàn",
    translations: ["hospital"],
    category: "nouns",
  },
  {
    hanzi: "椅子",
    pinyin: "yǐ zi",
    translations: ["chair"],
    category: "nouns",
  },
  {
    hanzi: "有",
    pinyin: "yǒu",
    translations: ["to have"],
    category: "verbs",
  },
  {
    hanzi: "月",
    pinyin: "yuè",
    translations: ["moon", "month"],
    category: "nouns",
  },
  {
    hanzi: "在",
    pinyin: "zài",
    translations: ["at", "in"],
    category: "others",
  },
  {
    hanzi: "再见",
    pinyin: "zài jiàn",
    translations: ["goodbye", "see you again later"],
    category: "verbs",
  },
  {
    hanzi: "怎么",
    pinyin: "zěn me",
    translations: ["how"],
    category: "pronouns",
  },
  {
    hanzi: "怎么样",
    pinyin: "zěn me yàng",
    translations: ["how about?"],
    category: "pronouns",
  },
  {
    hanzi: "这",
    pinyin: "zhè",
    translations: ["here", "this"],
    category: "pronouns",
  },
  {
    hanzi: "中国",
    pinyin: "Zhōng guó",
    translations: ["China"],
    category: "nouns",
  },
  {
    hanzi: "中午",
    pinyin: "zhōng wǔ",
    translations: ["noon", "midday"],
    category: "nouns",
  },
  {
    hanzi: "住",
    pinyin: "zhù",
    translations: ["to live"],
    category: "verbs",
  },
  {
    hanzi: "桌子",
    pinyin: "zhuō zi",
    translations: ["table", "desk"],
    category: "nouns",
  },
  {
    hanzi: "字",
    pinyin: "zì",
    translations: ["character"],
    category: "nouns",
  },
  {
    hanzi: "昨天",
    pinyin: "zuó tiān",
    translations: ["yesterday"],
    category: "nouns",
  },
  {
    hanzi: "坐",
    pinyin: "zuò",
    translations: ["to sit", "to take (a bus, airplane etc)"],
    category: "verbs",
  },
  {
    hanzi: "做",
    pinyin: "zuò",
    translations: ["to do", "to make"],
    category: "verbs",
  },
];
