export const SET_IS_DIALOG_OPEN = "SET_IS_DIALOG_OPEN";
export const SET_IS_RESULTS_DIALOG_OPEN = "SET_IS_RESULTS_DIALOG_OPEN";
export const SIGN_IN = "SIGN_IN";
export const FAILED_SIGN_IN = "FAILED_SIGN_IN";
export const TRY_SIGN_IN = "TRY_SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SIGN_OUT = "SIGN_OUT";
export const SET_SELECTED_HSK = "SET_SELECTED_HSK";
export const SET_SELECTED_MULTIPLE_CHOICE_ANSWER =
  "SET_SELECTED_MULTIPLE_CHOICE_ANSWER";
export const FETCH_HSK_WORDS = "FETCH_HSK_WORDS";
export const SIGN_IN_WITH_TOKEN = "SIGN_IN_WITH_TOKEN";
export const SET_MULTIPLE_CHOICE_QUESTIONS = "SET_MULTIPLE_CHOICE_QUESTIONS";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SUBMIT_MULTIPLE_CHOICE_QUESTIONS =
  "SUBMIT_MULTIPLE_CHOICE_QUESTIONS";
export const SET_MATCHING_GAME_CARDS = "SET_MATCHING_GAME_CARDS";
export const FLIP_CARD = "FLIP_CARD";
export const HANDLE_TRANSITION_END = "HANDLE_TRANSITION_END";
export const CLEAN_MATCHING_GAME = "CLEAN_MATCHING_GAME";
export const SET_IS_MATCHING_GAME_DIALOG_OPEN =
  "SET_IS_MATCHING_GAME_DIALOG_OPEN";
